name: ai_video_app
description: AI Video Generator App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  video_player: ^2.8.1
  dio: ^5.4.0                  # 🌟 ဒေါင်းလုဒ်အတွက်
  path_provider: ^2.1.2        # 🌟 ဖုန်း Storage ရှာဖို့
  permission_handler: ^11.3.0  # 🌟 Permission တောင်းဖို့
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
